PREFIX = /usr/local
INCLUDES = -I../liveMedia/include -I../groupsock/include -I../UsageEnvironment/include -I../BasicUsageEnvironment/include -fmodule-file=../liveMedia/liveMedia.framework/Modules/module.modulemap
# Default library filename suffixes for each library that we link with.  The "config.*" file might redefine these later.
libliveMedia_LIB_SUFFIX = $(DYNAMIC_LIB_SUFFIX)
##### Change the following for your environment:
